param(
  [string]$UpstreamPath = "..\upstream-deerflow",
  [string]$OutputPath = ".\generated\fbbp.config.yaml",
  [string]$ExtensionsTemplatePath = ".\configs\extensions_config.fbbp.example.json",
  [string]$ExtensionsOutputPath = ".\generated\extensions_config.fbbp.json",
  [switch]$Quiet
)

$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot 'common.ps1')

function Resolve-WorkspacePath {
  param(
    [string]$WorkspaceRoot,
    [string]$PathValue
  )

  if ([System.IO.Path]::IsPathRooted($PathValue)) {
    return [System.IO.Path]::GetFullPath($PathValue)
  }

  return [System.IO.Path]::GetFullPath((Join-Path $WorkspaceRoot $PathValue))
}

function Write-Utf8NoBomFile {
  param(
    [string]$Path,
    [string]$Content
  )

  $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

$workspaceRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$upstreamRoot = Resolve-Path (Join-Path $workspaceRoot $UpstreamPath)
$primaryConfig = Join-Path $upstreamRoot "config.yaml"
$fallbackConfig = Join-Path $upstreamRoot "config.example.yaml"
$sourceConfig = if (Test-Path $primaryConfig) { $primaryConfig } else { $fallbackConfig }
$sourceExtensions = Resolve-WorkspacePath -WorkspaceRoot $workspaceRoot -PathValue $ExtensionsTemplatePath

if (-not (Test-Path $sourceConfig)) {
  throw "Could not find upstream DeerFlow config source at: $sourceConfig"
}
if (-not (Test-Path $sourceExtensions)) {
  throw "Could not find DeerFlow extensions template at: $sourceExtensions"
}

$outputFull = Resolve-WorkspacePath -WorkspaceRoot $workspaceRoot -PathValue $OutputPath
$outputDir = Split-Path $outputFull -Parent
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
$extensionsOutputFull = Resolve-WorkspacePath -WorkspaceRoot $workspaceRoot -PathValue $ExtensionsOutputPath
$extensionsOutputDir = Split-Path $extensionsOutputFull -Parent
New-Item -ItemType Directory -Force -Path $extensionsOutputDir | Out-Null

$workspaceName = Split-Path $workspaceRoot -Leaf
$skillsPath = "../../$workspaceName/skills"
$configText = Get-Content $sourceConfig -Raw

if ($configText -notmatch "(?m)^skills:") {
  throw "Could not find 'skills:' section in upstream config.example.yaml"
}

$configText = [regex]::Replace(
  $configText,
  "(?m)^skill<local_path_removed>",
  "skills:`r`n  path: $skillsPath`r`n",
  1
)

$lines = $configText -split "\r?\n"
$replacedModel = $false
$replacedApiKey = $false
$replacedBaseUrl = $false

for ($i = 0; $i -lt $lines.Length; $i++) {
  $line = $lines[$i]
  $trimmed = $line.TrimStart()
  if ($trimmed.StartsWith('#')) {
    continue
  }

  if (-not $replacedModel -and $line -match '^(\s+)mode<local_path_removed>
    $lines[$i] = "$($Matches[1])model: `$LLM_MODEL"
    $replacedModel = $true
    continue
  }

  if (-not $replacedApiKey -and $line -match '^(\s+)api_ke<local_path_removed>
    $lines[$i] = "$($Matches[1])api_key: `$OPENAI_API_KEY"
    $replacedApiKey = $true
    continue
  }

  if (-not $replacedBaseUrl -and $line -match '^(\s+)base_ur<local_path_removed>
    $lines[$i] = "$($Matches[1])base_url: `$OPENAI_BASE_URL"
    $replacedBaseUrl = $true
    continue
  }
}

$configText = $lines -join "`r`n"

$header = @(
"# Auto-generated config for FBBP research workspace",
  "# Generated by: scripts/prepare_deerflow_config.ps1",
  "# Edit models, API keys, MCP settings, and sandbox configuration before running.",
  ""
) -join "`r`n"

Write-Utf8NoBomFile -Path $outputFull -Content ($header + $configText)
Write-Utf8NoBomFile -Path $extensionsOutputFull -Content (Get-Content $sourceExtensions -Raw)
Sync-DefaultFbbpAgent | Out-Null

$outputResolved = (Resolve-Path $outputFull).Path
$extensionsResolved = (Resolve-Path $extensionsOutputFull).Path

if (-not $Quiet) {
  Write-Host "Generated config:" $outputResolved
  Write-Host "Generated extensions config:" $extensionsResolved
  Write-Host "Next steps:"
  Write-Host "  1) Review models and API keys in the generated config"
  Write-Host "  2) Adjust the generated extensions config only if you need extra MCP servers"
  Write-Host "  3) Start DeerFlow with:"
  Write-Host "     cd $upstreamRoot"
  Write-Host "     `$env:DEER_FLOW_CONFIG_PATH = '$outputResolved'"
  Write-Host "     `$env:DEER_FLOW_EXTENSIONS_CONFIG_PATH = '$extensionsResolved'"
  Write-Host "     make dev"
}
